Those are notes for course on DataCamp:
https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-1-python-basics?ex=1

In [ ]:
# Addition and subtraction
print(5 + 5)
print(5 - 5)

# Multiplication and division
print(3 * 5)
print(10 / 2)

# Exponentiation (Potęgowanie)
print(4 ** 2)

# Modulo (Reszta z dzielenia)
print(18 % 7)

# How much is your $100 worth after 7 years?
print(100*(1.1**7))

In [3]:
a = 3.14
b = 30
c = True
d = "string"
e = 'string'

for x in a,b,c,d,e:
    print(type(x))

<class 'float'>
<class 'int'>
<class 'bool'>
<class 'str'>
<class 'str'>


In [9]:
pi_string = "3.1415926"
pi2 = float(pi_string)

print (pi2 + 5)
print ("============================================")
print (pi_string +5)

8.1415926


TypeError: must be str, not int

# Lists

In [10]:
[1+2, "a"*5, 3]

[3, 'aaaaa', 3]

In [14]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv]]

# Print out house

print(house)

# Print out the type of house

print(type(house))


[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0]]
<class 'list'>


In [34]:
#List indexes

List = ["Monia0", 'Adam1', 'Wojtas2', 'Mama3', "Babcia4", 5, 6]

print(List[0])
print(List[3])

#Negative indexing (-1 is the last element of list)
print(List[-0])
print(List[-1])
print(List[-3])

Monia0
Mama3
Monia0
6
Babcia4


In [36]:
###  SLICING  ###
print("==================================================== SLICING ====================================================")
print(List[1:4])
print(List[:4])
print(List[1:])

print(List[1] + List[4])
print(List[5] + List[6])
print(List[1] + List[6])

print(List[-4:])

==================================================== SLICING ====================================================
['Adam1', 'Wojtas2', 'Mama3']
['Monia0', 'Adam1', 'Wojtas2', 'Mama3']
['Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 6]
Adam1Babcia4
11


TypeError: must be str, not int

In [60]:
### LIST MANIPULATION ###
List = ["Monia0", 'Adam1', 'Wojtas2', 'Mama3', "Babcia4", 5, 6]

List[6] = "Tata6"

List[:1] = ["Mooonia0"]

List[6:] = "lala"
List2 = List +[7, 8]
print(List)
print(List2)

### REMOVING ###
print('=========================REMOVING===========================')
del(List[-1])
del(List2)
print(List)
print(List2)

['Mooonia0', 'Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 'l', 'a', 'l', 'a']
['Mooonia0', 'Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 'l', 'a', 'l', 'a', 7, 8]
=========================REMOVING===========================
['Mooonia0', 'Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 'l', 'a', 'l']


NameError: name 'List2' is not defined

In [40]:
### Adding and Removing to list ###
List = ["Monia0", 'Adam1', 'Wojtas2', 'Mama3', "Babcia4", 5, 6]

In [55]:
### Reference vs coping values ###
List = ["Monia0", 'Adam1', 'Wojtas2', 'Mama3', "Babcia4", 5, 6]

Reference = List

print("Reference:", Reference)

Reference[3] = "As this is reference value will change as well on primary List"

print("List:", List)
print("=========================================================================================================================")
List = ["Monia0", 'Adam1', 'Wojtas2', 'Mama3', "Babcia4", 5, 6]
Copy = list(List)
Copy2 = List[:]

Copy[3] = "As this is copy value will  not change on primary List but only on Copy"
print("List:", List)
print("Copy:", Copy)
print("Copy2:", Copy2)

Reference: ['Monia0', 'Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 6]
List: ['Monia0', 'Adam1', 'Wojtas2', 'As this is reference value will change as well on primary List', 'Babcia4', 5, 6]
List: ['Monia0', 'Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 6]
Copy: ['Monia0', 'Adam1', 'Wojtas2', 'As this is copy value will  not change on primary List but only on Copy', 'Babcia4', 5, 6]
Copy2: ['Monia0', 'Adam1', 'Wojtas2', 'Mama3', 'Babcia4', 5, 6]


In [63]:
#Comment
#The ; sign is used to place commands on the same line. The following two code chunks are equivalent:

print("separator")
print("check")

print("separator2"); print('check2')

separator
check
separator2
check2


In [74]:
### BUILT-IN FUNCTIONS ###
print(round(3.1456789, 4))
print(max(1,2,3))
print(len("Mama"))
help(round)
# [,ndigits] is an optional argument
?sorted

print(sorted((1,2,3,4),reverse = True))

3.1457
3
4
Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.

[4, 3, 2, 1]


In [89]:
### Methods: index, counts and append for Lists ###

Lista_Moni = ["kwiatki",'bratki', "stokrotki", 'konwalie', "bratki", "dalie", "bratki"]
print(Lista_Moni.index("stokrotki"))
print(Lista_Moni.count("bratki"))
print(Lista_Moni.append("fiołki"))
print(Lista_Moni)
new = [ ]
new.append(1)
print(new)

2
3
None
['kwiatki', 'bratki', 'stokrotki', 'konwalie', 'bratki', 'dalie', 'bratki', 'fiołki']
[1]


In [90]:
%%cmd
import numpy as np
pip install numpy

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

(Python_DataCamp) C:\Users\Wojtek Biedzinski\Documents\MK PYTHON\UDACITY Python for data analysys\JUPYTER>pip install numpy

(Python_DataCamp) C:\Users\Wojtek Biedzinski\Documents\MK PYTHON\UDACITY Python for data analysys\JUPYTER>

In [93]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [111]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_height = np.array(height)
np_weight = np.array(weight)

print(height)
print(np_height)

### ELEMENT WISE CALCULATION ###
bmi = np_weight/np_height **2
print(bmi)

[1.73, 1.68, 1.71, 1.89, 1.79]
[ 1.73  1.68  1.71  1.89  1.79]
[ 21.85171573  20.97505669  21.75028214  24.7473475   21.44127836]


In [117]:
x = [4 , 9 , 6, 3, 1]
x[1]

y = np.array(x)
y[1]

f = np.array(y>3)
print(f)
# Print all numbers from y which fullfil f
print(y[f])

[ True  True  True False False]
[4 9 6]


In [119]:
print(np.array([True, 1, 2]) + np.array([3, 4, False]))
print("=========================================")

print(np.array([True, 1, 2, 3, 4, False]))
print(np.array([4, 3, 0]) + np.array([0, 2, 2]))
print(np.array([1, 1, 2]) + np.array([3, 4, -1]))
print(np.array([0, 1, 2, 3, 4, 5]))

[4 5 2]
[1 1 2 3 4 0]
[4 5 2]
[4 5 1]
[0 1 2 3 4 5]


In [127]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
np_x = np.array(x)
print(np_x)
print('========================')
print(np_x[:,0])
print('========================')
print(np_x[:,1])
print('========================')
print(np_x[:,])
print('========================')
print(np_x[0,])
print('========================')
print(np_x[0,0])

[['a' 'b']
 ['c' 'd']]
['a' 'c']
['b' 'd']
[['a' 'b']
 ['c' 'd']]
['a' 'b']
a


In [136]:

np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print(np_mat * 2)
print("=========== Dodawanie liczb do macierzy =================")
print(np_mat + np.array([10, 10]))
print("=========== Dodawanie macierzy =================")
print(np_mat + np_mat)
print("=========== Mnozenie macierzy przez wektor =================")

conversion = np.array([0.05, 0.2])
print(conversion)
print(np_mat * conversion)

[[ 2  4]
 [ 6  8]
 [10 12]]
=========== Dodawanie liczb do macierzy =================
[[11 12]
 [13 14]
 [15 16]]
=========== Dodawanie macierzy =================
[[ 2  4]
 [ 6  8]
 [10 12]]
=========== Mnozenie macierzy przez wektor =================
[ 0.05  0.2 ]
[[ 0.05  0.4 ]
 [ 0.15  0.8 ]
 [ 0.25  1.2 ]]


In [137]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
# Print mean height (first column)
avg = np.mean(np_mat[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_mat[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_mat[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_mat[:,0], np_mat[:,1])
print("Correlation: " + str(corr))

Average: 3.0
Median: 3.0
Standard Deviation: 1.63299316186
Correlation: [[ 1.  1.]
 [ 1.  1.]]


In [142]:
positions = ['GK', 'M', 'A', 'D', 'GK', 'A'] 
heights = [191, 184, 185, 180, 192, 184]

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']
print(gk_heights)

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(None))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(None))

[191 192]
Median height of goalkeepers: None
Median height of other players: None


In [153]:
np_mat = np.array([[1, 2, 3]])
imiona = np.array([["Monia", "Wojtas", "Adaś"]])

print(np_mat)
print(imiona)
print('===================================================')
number = np_mat[imiona == "Monia"]
print("Które miejsce ma Monia w tabeli np_mat:", number)
number = np_mat[imiona == "Adaś"]
print("Które miejsce ma Adaś w tabeli np_mat:", number)

[[1 2 3]]
[['Monia' 'Wojtas' 'Adaś']]
Które miejsce ma Monia w tabeli np_mat: [1]
Które miejsce ma Adaś w tabeli np_mat: [3]
